// Generated by CoffeeScript 1.6.2
(function() {
  Deps.autorun(function() {
    return Meteor.subscribe("last_posts");
  });

  this.Posts = new Meteor.Collection('posts');

  Template.blog_edit_panel.events({
    'click #form_newpost_submit': function(e) {
      var form_fecha, form_imagen, form_texto, form_titulo;

      e.preventDefault();
      form_titulo = $('#form_newpost_titulo').val();
      form_texto = $('#form_newpost_texto').val();
      form_imagen = '';
      form_fecha = moment().format("YYYY-MM-DD");
      return Posts.insert({
        titulo: form_titulo,
        texto: form_texto,
        imagen: form_imagen,
        fecha: form_fecha
      });
    },
    'click .delete_post_btn': function(e) {
      e.preventDefault();
      return Posts.remove({
        "_id": $(e.target).data('id')
      });
    },
    'click .edit_post_btn': function(e) {
      var post_id;

      e.preventDefault();
      post_id = $(e.target).data('id');
      return $('#edit_post_' + post_id).fadeIn();
    },
    'click .edit_post_submit': function(e) {
      var post_id;

      e.preventDefault();
      post_id = $(e.currentTarget).attr('data_id');
      Posts.update({
        '_id': post_id
      }, {
        titulo: $('#edit_post_titulo_' + post_id).val(),
        texto: $('#edit_post_texto_' + post_id).val(),
        imagen: $('#edit_post_imagen_' + post_id).val(),
        fecha: moment().format("YYYY-MM-DD")
      });
      return $('#edit_post_' + post_id).fadeOut();
    }
  });

  Template.blog_edit_panel.items = function() {
    return Posts.find({}).fetch();
  };

}).call(this);
